# -*- coding: utf-8 -*-
"""spotify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMWoRTQf4TRa9zPEf7aaPbJBjMI3WGkR
"""

import streamlit as st
import requests

# --- 1. APP CONFIG ---
st.set_page_config(page_title="Streamlitify Pro", layout="wide", page_icon="🎵")

# --- 2. CSS (Text-only headers + Animated Track Images) ---
st.markdown("""
    <style>
    .stApp { background-color: #000000; color: white; }
    [data-testid="stSidebar"] { background-color: #000000; border-right: 1px solid #282828; }

    /* Text-based Artist Names for the top row */
    .artist-name-header {
        font-size: 24px;
        font-weight: bold;
        color: #1DB954;
        text-align: center;
        padding: 20px;
        border: 1px solid #333;
        border-radius: 15px;
        transition: 0.3s;
    }
    .artist-name-header:hover {
        background-color: #1DB954;
        color: black;
    }

    /* Animated Track Images with Hover Effect */
    .track-card {
        transition: transform 0.4s ease, box-shadow 0.4s ease;
        border-radius: 15px;
        overflow: hidden;
    }
    .track-card:hover {
        transform: translateY(-10px) scale(1.02);
        box-shadow: 0px 10px 30px rgba(29, 185, 84, 0.4);
    }

    .stButton>button {
        background-color: #1DB954;
        color: white;
        border-radius: 20px;
        font-weight: bold;
        width: 100%;
        border: none;
    }
    </style>
    """, unsafe_allow_html=True)

# --- 3. SESSION STATE ---
if "view" not in st.session_state:
    st.session_state.view = "home"
if "selected_artist" not in st.session_state:
    st.session_state.selected_artist = None
if "playing_track" not in st.session_state:
    st.session_state.playing_track = None
if "liked_songs" not in st.session_state:
    st.session_state.liked_songs = []

# --- 4. API ENGINE ---
BASE_URL = "https://discoveryprovider.audius.co/v1"

def fetch_tracks(query):
    try:
        url = f"{BASE_URL}/tracks/search?query={query}&app_name=STREAMLITIFY_PRO_V7"
        r = requests.get(url, timeout=5)
        return r.json().get('data', [])
    except:
        return []

# --- 5. SIDEBAR NAVIGATION ---
with st.sidebar:
    st.title("🎵 Streamlitify")
    if st.button("🏠 Home"):
        st.session_state.view = "home"
        st.rerun()
    if st.button("🔍 Search"):
        st.session_state.view = "search"
        st.rerun()
    if st.button("📚 Your Library"):
        st.session_state.view = "library"
        st.rerun()

# --- 6. MAIN CONTENT ---

# VIEW: LIBRARY
if st.session_state.view == "library":
    st.header("Your Library")
    if not st.session_state.liked_songs:
        st.info("No liked songs yet.")
    else:
        for i, track in enumerate(st.session_state.liked_songs):
            c1, c2 = st.columns([5, 1])
            c1.write(f"❤️ **{track['title']}**")
            if c2.button("Play", key=f"lib_play_{i}"):
                st.session_state.playing_track = track
                st.rerun()

# VIEW: SEARCH
elif st.session_state.view == "search":
    st.header("Global Search")
    query = st.text_input("", placeholder="Search for anything...")
    if query:
        results = fetch_tracks(query)
        for t in results[:10]:
            col1, col2 = st.columns([5, 1])
            col1.write(f"**{t['title']}** - {t['user']['name']}")
            if col2.button("▶️", key=f"search_{t['id']}"):
                st.session_state.playing_track = {
                    "title": t['title'],
                    "url": f"{BASE_URL}/tracks/{t['id']}/stream?app_name=ST",
                    "img": t.get('artwork', {}).get('150x150', "https://via.placeholder.com/150")
                }
                st.rerun()

# VIEW: ARTIST PROFILE
elif st.session_state.view == "artist_profile":
    artist = st.session_state.selected_artist
    if st.button("← Back"):
        st.session_state.view = "home"
        st.rerun()

    st.header(f"Tracks for {artist}")
    tracks = fetch_tracks(artist)
    for t in tracks[:10]:
        c1, c2, c3 = st.columns([4, 1, 1])
        c1.write(f"**{t['title']}**")
        if c2.button("Play", key=t['id']):
            st.session_state.playing_track = {
                "title": t['title'],
                "url": f"{BASE_URL}/tracks/{t['id']}/stream?app_name=ST",
                "img": t.get('artwork', {}).get('150x150', "https://via.placeholder.com/150")
            }
            st.rerun()
        if c3.button("❤️ Like", key=f"like_{t['id']}"):
            new_like = {"title": t['title'], "url": f"{BASE_URL}/tracks/{t['id']}/stream?app_name=ST"}
            if new_like not in st.session_state.liked_songs:
                st.session_state.liked_songs.append(new_like)
                st.toast("Saved!")

# VIEW: HOME
else:
    st.title("Good Evening")

    # --- TOP SECTION: POPULAR SINGERS (TEXT ONLY) ---
    st.subheader("Popular Singers")
    singers = ["Adele", "Billie Eilish", "Tamino"]
    s_cols = st.columns(len(singers))
    for i, name in enumerate(singers):
        with s_cols[i]:
            st.markdown(f'<div class="artist-name-header">{name}</div>', unsafe_allow_html=True)
            if st.button("Explore", key=f"singer_btn_{i}"):
                st.session_state.selected_artist = name
                st.session_state.view = "artist_profile"
                st.rerun()

    st.write("---")

    # --- BOTTOM SECTION: TRENDING TRACKS (ANIMATED PICTURES) ---
    st.subheader("Trending Mixes")
    trending_mixes = [
        {"name": "Midnight Chill", "img": "https://picsum.photos/id/12/400/400", "query": "Chill"},
        {"name": "Focus Beats", "img": "https://picsum.photos/id/15/400/400", "query": "Lofi"},
        {"name": "Top Pop", "img": "https://picsum.photos/id/26/400/400", "query": "Pop"},
        {"name": "Indie Vibes", "img": "https://picsum.photos/id/37/400/400", "query": "Indie"}
    ]

    t_cols = st.columns(4)
    for i, mix in enumerate(trending_mixes):
        with t_cols[i]:
            st.markdown(f'<div class="track-card"><img src="{mix["img"]}" style="width:100%"></div>', unsafe_allow_html=True)
            if st.button(f"Play {mix['name']}", key=f"mix_{i}"):
                st.session_state.selected_artist = mix['query']
                st.session_state.view = "artist_profile"
                st.rerun()

# --- 7. PLAYER ---
if st.session_state.playing_track:
    st.markdown("---")
    curr = st.session_state.playing_track
    st.write(f"🎧 Now Playing: **{curr['title']}**")
    st.audio(curr['url'], format="audio/mp3", autoplay=True)